### ISSUE TITLE
Consistent README files for the GitHub home page and repos.   

### ISSUE THREAD

**Issue by mark-terminusdb** [terminusdb/terminusdb-docs#73]
Review and implement consistent structure and messaging for:

- Server: https://github.com/terminusdb/terminusdb
- Docs: https://github.com/terminusdb/terminusdb-docs
- Python client: https://github.com/terminusdb/terminusdb-client-python
- JavaScript client: https://github.com/terminusdb/terminusdb-client-js
- Bootstrap: https://github.com/terminusdb/terminusdb-bootstrap

Use consistent language/narrative across readme files and docs pages when describing the same components such as introductions and features.

**Comment by spl** [comment]
I added the Python and JavaScript clients above, because they are key parts of our infrastructure. Should others be considered? These are pinned on the organization page:
- terminusdb-store: https://github.com/terminusdb/terminusdb-store/blob/main/README.md
- terminusdb-bootstrap: https://github.com/terminusdb/terminusdb-bootstrap/blob/main/README.md

**Comment by spl** [comment]
I made progress. It could be improved upon, but it's not a priority now.
